#!/bin/bash
#SBATCH -J mash
#SBATCH --partition=shas
#SBATCH --qos=normal
#SBATCH --ntasks=4
#SBATCH -t 12:00:00
#SBATCH --error mash-%j.err
#SBATCH -o mash-%j.out

enve=/projects/kim45@colostate.edu/Software/enveomics/Scripts
THR=4
mash=/projects/kim45@colostate.edu/Software/mash-Linux64-v2.3/mash

cd /pl/active/conant-csu/Minjae/nit_mg/07.mash

readlink -f *.msh > mash_list.txt ;

echo "List created"

"$mash" paste mash.all -l mash_list.txt ;

echo "ready to make distance matrix"

"$mash" dist -t mash.all.msh mash.all.msh > Mash_dist.txt ;

echo "Done"
